appsite/appsite/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, re_path
from django.conf import settings

urlpatterns = [
    path('apps/', include('neon.urls')),
    path('chemical/', include('structure.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('resolver.urls')),
    re_path('^api-auth', include('rest_framework.urls', namespace='rest_framework')),
    # path('__debug__/', include('debug_toolbar.urls')),
    path('', lambda request: redirect('apps/', permanent=False)),
]

if not settings.TESTING:
    urlpatterns = [
        *urlpatterns,
        path("__debug__/", include("debug_toolbar.urls")),
    ]

appsite/neon/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('cir', views.cir, name="cir"),
    path('neon/<str:string>', views.neon),
    path('neon/compounds/<int:cid>', views.compounds, name="compounds"),
    path('neon/compound-images/<int:cid>', views.compound_images, name="compound-images"),
    path('neon/records/<int:rid>', views.records, name="records"),
    path('neon/record-images/<int:rid>', views.record_images, name="record-images"),
    #path('images/<str:string>', views.images, name="images-string"),
    path('sandbox/', views.sandbox, name="sandbox"),
    path('', views.cover, name="cover"),
]

appsite/resolver/urls.py
from django.urls import include, path, re_path

from rest_framework.routers import DefaultRouter
from rest_framework.settings import api_settings

from . import views
from . import routers

router = routers.ResolverApiRouter(trailing_slash=False)
router.register('inchis', views.InChIViewSet)
router.register('inchitypes', views.InChITypeViewSet)
router.register('organizations', views.OrganizationViewSet)
router.register('publishers', views.PublisherViewSet)
router.register('structures', views.StructureViewSet)
router.register('structureparents', views.StructureParentStructureViewSet)
router.register('structureinchiassociations', views.StructureInChIAssociationViewSet)
router.register('entrypoints', views.EntryPointViewSet)
router.register('endpoints', views.EndPointViewSet)
router.register('mediatypes', views.MediaTypeViewSet)



urlpatterns = [

    re_path(r'', include(router.urls)),

    path('_self',
        views.EntryPointViewSet.as_view({'get': 'get_self_entrypoint'}),
        name='entrypoints-self'),

    path('structures/<pk>/relationships/<related_field>',
         views.StructureRelationshipView.as_view(), {'source': 'relationships'},
         name='structures-relationships'),
    path('structures/<pk>/<related_field>',
         views.StructureViewSet.as_view({'get': 'retrieve_related'}), {'source': 'field'},
         name='structures-related'),

    path('structureparents/<pk>/relationships/<related_field>',
         views.StructureParentStructureRelationshipView.as_view(), {'source': 'relationships'},
         name='structureparents-relationships'),
    path('structureparents/<pk>/<related_field>',
         views.StructureParentStructureViewSet.as_view({'get': 'retrieve_related'}), {'source': 'field'},
         name='structureparents-related'),

    path('inchis/<pk>/relationships/<related_field>',
         views.InChIRelationshipView.as_view(), {'source': 'relationships'},
         name='inchis-relationships'),
    path('inchis/<pk>/<related_field>',
         views.InChIViewSet.as_view({'get': 'retrieve_related'}), {'source': 'field'},
         name='inchis-related'),

    path('structureinchiassociations/<pk>/relationships/<related_field>',
        views.StructureInChIAssociationRelationshipView.as_view(), {'source': 'relationships'},
        name='structureinchiassociations-relationships'),
    path('structureinchiassociations/<pk>/<related_field>',
        views.StructureInChIAssociationViewSet.as_view({'get': 'retrieve_related'}), {'source': 'field'},
        name='structureinchiassociations-related'),

    path('inchitypes/<pk>/relationships/<related_field>',
         views.InChITypeRelationshipView.as_view(), {'source': 'relationships'},
         name='inchitypes-relationships'),
    path('inchitypes/<pk>/<related_field>',
         views.InChITypeViewSet.as_view({'get': 'retrieve_related'}), {'source': 'field'},
         name='inchitypes-related'),

    path('publishers/<pk>/relationships/<related_field>',
        views.PublisherRelationshipView.as_view(), {'source': 'relationships'},
        name='publishers-relationships'),
    path('publishers/<pk>/<related_field>',
        views.PublisherViewSet.as_view({'get': 'retrieve_related'}), {'source': 'field'},
        name='publishers-related'),

    path('entrypoints/<pk>/relationships/<related_field>',
        views.EntryPointRelationshipView.as_view(), {'source': 'relationships'},
        name='entrypoints-relationships'),
    path('entrypoints/<pk>/<related_field>',
        views.EntryPointViewSet.as_view({'get': 'retrieve_related'}), {'source': 'field'},
        name='entrypoints-related'),

    path('organizations/<pk>/relationships/<related_field>',
        views.OrganizationRelationshipView.as_view(), {'source': 'relationships'},
        name='organizations-relationships'),
    path('organizations/<pk>/<related_field>',
        views.OrganizationViewSet.as_view({'get': 'retrieve_related'}), {'source': 'field'},
        name='organizations-related'),

    path('endpoints/<pk>/relationships/<related_field>',
        views.EndPointRelationshipView.as_view(), {'source': 'relationships'},
        name='endpoints-relationships'),
    path('endpoints/<pk>/<related_field>',
        views.EndPointViewSet.as_view({'get': 'retrieve_related'}), {'source': 'field'},
        name='endpoints-related'),

    path('mediatypes/<pk>/relationships/<related_field>',
        views.MediaTypeRelationshipView.as_view(), {'source': 'relationships'},
        name='mediatypes-relationships'),
    path('mediatypes/<pk>/<related_field>',
        views.MediaTypeViewSet.as_view({'get': 'retrieve_related'}), {'source': 'field'},
        name='mediatypes-related'),

]

appsite/urls.py
#from django.conf.urls.defaults import *
from django.conf.urls import *
from django.contrib import admin
from django.urls import path
from django.views.decorators.cache import cache_page

import structure.views
import file.views
import media.views
import network.views

#import database.csls.views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    path('simple/', include('simple.urls')),
    path('admin/', admin.site.urls),
]

# urlpatterns = patterns('',
# 	url(r'^apps/', include('chemical.apps.urls')),
# 	url(r'^activity/', include('chemical.activity.urls')),
# 	url(r'^identifier/', include('chemical.identifier.urls')),
# 	#(r'^database/', include('chemical.database.urls')),
# 	url(r'^database/', include('chemical.database.urls')),
# 	#(r'^database/pdb', include('chemical.database.ligand.urls')),
# 	#(r'^structure/openid/', include('django_openid_auth.urls')),
# 	#(r'^dbmedia', media.views.db_media),
# 	#(r'^media_config', media.views.media_config),
# 	url(r'^media', media.views.media),
# 	#(r'^network', network.views.network),
# 	#(r'^file/test', file.views.test),
# 	#(r'^file/list', file.views.file_list),
# 	#(r'^file/upload_progress', file.views.upload_progress),
# 	#(r'^file/upload', file.views.upload),
# 	#(r'^file/preload', file.views.preload),
# 	#(r'^file/(?P<key>.{32})/fields', file.views.fields),
# 	#(r'^file/(?P<key>.{32})', file.views.get),
# 	#(r'^file', file.views.post),
# 	#(r'^file/(?P<file_identifier>.+)/database_tab', file.views.database_tab),
# 	#(r'^file/(?P<file_identifier>.+)/identifier_tab', file.views.identifier_tab),
# 	#(r'^file/(?P<file_identifier>.+)/structure_tab', file.views.structure_tab),
# 	#(r'^file/(?P<file_identifier>.+)/delete', file.views.delete),
# 	#(r'^file/(?P<file_identifier>.+)/download', file.views.download),
# 	#(r'^file/(?P<file_identifier>.+)/add/(?P<chemical_string>.+)', file.views.add),
# 	#(r'^file/(?P<file_identifier>.+)/preload', file.views.preload),
# 	#(r'^file/processing_status/(?P<string>.{32})$', file.views.processing_status),
# 	#(r'^file/(?P<file_identifier>.+)/(?P<record_identifier>.+)', file.views.view_structure),
# 	#(r'^file/(?P<file_identifier>.+)', file.views.view),
# 	#(r'^file', file.views.view),
# 	#url(r'^structure_opsin_resolver/(?P<name>.+)$', cache_page(structure.views.opsin_resolver, 60 * 60 * 24)),
# 	url(r'^structure_opsin_resolver/(?P<name>.+)$', cache_page(60*60*24)(structure.views.opsin_resolver)),
# 	#(r'^structure/name/(?P<string>.+)', structure.views.name),
# 	#(r'^structure/test$', structure.views.test),
# 	#(r'^structure/name$', structure.views.name),
# 	#(r'^structure/documentation$', structure.views.structure_documentation),
# 	#(r'^structure/statistic/seconds$', cache_page(structure.views.statistic_seconds, 10)),
# 	#(r'^structure/statistics$', cache_page( structure.views.statistics, 60 * 60 * 24 * 10)),
# 	#(r'^structure/editor$', structure.views.editor),
# 	#(r'^structure/test/(?P<string>.+)', structure.views.test),
# 	#(r'^structure/(?P<string>.+)/twirl_cached/(?P<dom_id>.+)$', structure.views.twirl_cache),
# 	url(r'^structure_documentation$', structure.views.structure_documentation),
# 	#url(r'^structure/(?P<string>.+)/twirl_cached/(?P<dom_id>.+)$', cache_page(structure.views.twirl_cache, 60 * 60 * 240)),
# 	url(r'^structure/(?P<string>.+)/twirl_cached/(?P<dom_id>.+)$', cache_page(60*60*240)(structure.views.twirl_cache)),
# 	url(r'^structure/(?P<string>.+)/chemdoodle_cached/(?P<dom_id>.+)$', structure.views.chemdoodle_cache),
# 	#url(r'^structure/(?P<string>.+)/(?P<representation>.+)/(?P<format>xml)', cache_page(structure.views.identifier, 60 * 60 * 24)),
# 	url(r'^structure/(?P<string>.+)/(?P<representation>.+)/(?P<format>xml)', cache_page(60*60*24)(structure.views.identifier)),
# 	#url(r'^structure/(?P<string>.+)/(?P<representation>.+)$', cache_page(structure.views.identifier, 60 * 60 * 24)),
# 	url(r'^structure/(?P<string>.+)/(?P<representation>.+)$', cache_page(60*60*24)(structure.views.identifier)),
# 	url(r'^structure/(?P<string>.+)$', structure.views.structure),
# 	url(r'^structure$', structure.views.structure),
#
#     # Uncomment the next line to enable admin documentation:
#     # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
#
#     # Uncomment the next line to enable the admin:
#     # (r'^admin/(.*)', admin.site.root),
# )

appsite/structure/forms.py
from django import forms


# class ChemicalStringInput(forms.Form):
#     chemicalString = forms.CharField(label="", widget=forms.TextInput(attrs={'size': '80'}))


class ResolverInput(forms.Form):
    identifier = forms.CharField(label="Structure Identifier", widget=forms.TextInput(attrs={'size': '20'}))
    representation = forms.ChoiceField(
        label="to representation:",
        choices=(
            ('stdinchikey', 'Standard InChIKey'),
            ('stdinchi', 'Standard InChI'),
            ('smiles', 'SMILES'),
            ('ficts', 'FICTS Identifier'),
            ('ficus', 'FICuS Identifier'),
            ('uuuuu', 'uuuuu Identifier'),
            ('hashisy', 'Cactvs HASHISY'),
            ('file?format=sdf', 'SD File'),
            ('names', 'Names'),
            ('iupac_name', 'IUPAC Name'),
            ('cas', 'CAS Registry Number'),
            #('chemspider_id', 'ChemSpider ID'),
            ('image', 'GIF Image'),
            ('twirl', 'TwirlyMol (3D)'),
            ('mw', 'Molecular Weight'),
            ('formula', 'Chemical Formula'),
            ('h_bond_donor_count', 'Number of Hydrogen Bond Donors'),
            ('h_bond_acceptor_count', 'Number of Hydrogen Bond Acceptors'),
            ('h_bond_center_count', 'Number of Hydrogen Bond Acceptors and Donors'),
            ('rule_of_5_violation_count', 'Number of Rule of 5 Violations'),
            ('rotor_count', 'Number of Freely Rotatable Bonds'),
            ('effective_rotor_count', 'Number of Effectively Rotatable Bonds'),
            ('ring_count', 'Number of Rings'),
            ('ringsys_count', 'Number of Ring Systems'),
        )
    )


# class ChemicalNameInput(forms.Form):
#     nameString = forms.CharField(label="", widget=forms.TextInput(attrs={'size': '50'}))


# class ChemicalFileUpload(forms.Form):
#     file = forms.FileField(label="File:")

appsite/neon/templates/cir.html
{% extends "neon-base.html" %}
{# Load the tag library #}
{% load static %}
{% load django_bootstrap5 django_bootstrap_input_group %}

{% block body_class %}d-flex flex-column h-100{% endblock %}

{% block main %}
    <div class="container-fluid mt-5 p-5 bg-light" id="form-container">
        {% include 'editor.html' %}
        {% include 'structure-form.html' %}
    </div>

    <div class="container-fluid p-5" id="getting-started-container">
        <h1 class="display-6">Getting started.</h1>
        <p class="lead">
            This service works as a resolver for different chemical structure identifiers and allows one to
            convert a
            given structure identifier into another representation or structure identifier. It can help you
            identify
            and find the chemical structure if you have an identifier such as an InChIKey. You can either use
            the resolver web form above or use the following simple URL API scheme:
        </p>

        <div class="bg-light border-start border-3 overflow-auto mt-3 mb-3">
            <p class="fs-2 p-3 pb-1">{{ host }}/chemical/structure/<strong
                    class="text-secondary">identifier</strong>/<strong
                    class="text-primary">representation</strong></p>
        </div>

        <p class="lead">
            The service returns the requested new structure representation with a corresponding MIME-Type
            specification
            (in most cases <span class="">MIME-Type: "text/plain"</span>). If a requested URL is not resolvable
            for
            the service a <span class="term">HTML 404 status</span> message is returned.
        </p>
        <p><small>
            <span class="badge bg-warning text-dark">Note:</span> Triple bonds in SMILES strings represented by
            '<em>#</em>' have to be URL-escaped as <span class="badge bg-dark-subtle text-dark">%23</span>
            (e.g. the
            SMILES string of '<em>ethyne</em>' has to be specified as
            <span class="badge bg-dark-subtle text-dark">C%23C</span> instead of '<em>C#C</em>' if
            encoded as part of a URL). Similarly, question marks, which can occur in InChI, need to be
            URL-escaped as <span class="badge bg-dark-subtle text-dark">%3F</span>.
        </small></p>
    </div>

{% endblock main %}

{% block javascript %}
    <script src="{% static 'neon/assets/jquery/jquery-3.6.4.min.js' %}"></script>
    <script src="{% static 'neon/assets/jsme/jsme.nocache.js' %}"></script>
    <script src="{% static 'neon/assets/neon.js' %}"></script>
    <!--<script src="/chemical/structure/CCO/twirl?width=255&height=255&dom_id=twirl_example"></script>-->
{% endblock javascript %}

appsite/neon/templates/compound.html
{% extends "neon-base.html" %}

{% block body_class %}d-flex flex-column h-100{% endblock %}

{% block main %}
<main class="flex-shrink-0">
    <div class="container-fluid p-5" id="main-container">
        <div class="align-items-center mt-5">
            <h1>CID {{ compound.id }}</h1>
            <div class="mb-2">
                <div class="btn-group" role="group">
                    {% if compound.get_previous_by_added.id %}
                        <a href="{% url 'compounds' compound.get_previous_by_added.id %}"
                           class="btn btn-sm btn-light" type="button">
                            <i class="bi bi-caret-left-fill"></i> Previous
                        </a>
                    {% else %}
                        <a href="" class="btn btn-sm btn-light" type="button">
                            <i class="bi bi-caret-left-fill"></i> Previous
                        </a>
                    {% endif %}
                    {% if compound.get_next_by_added.id %}
                        <a href="{% url 'compounds' compound.get_next_by_added.id %}"
                           class="btn btn-sm btn-light" type="button">
                            Next <i class="bi bi-caret-right-fill"></i>
                        </a>
                    {% else %}
                        <a href="" class="btn btn-sm btn-light" type="button">
                            Next <i class="bi bi-caret-right-fill"></i>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
        <hr class="bg-secondary mb-4">

        <div class="row align-items-start">
            <div class="col col-xxl-3 col-xl-3 col-lg-4 col-md-12 col-sm-12 col-12">
                <div class="row">
                    {% if compound.id %}
                        <figure class="figure">
                            <img src="{% url 'compound-images' compound.id %}"
                                 class="figure-img img-fluid img-thumbnail rounded"
                                 style="min-width: 260px; min-height: 260px;" alt="structure of CID {{ compound.id }}">
                            <figcaption class="figure-caption">Structure of NCICADD:CID {{ compound.id }}</figcaption>
                        </figure>
                    {% endif %}
                </div>
            </div>
            <div class="col col-xxl-9 col-xl-9 col-lg-8 col-md-12 col-sm-12 col-12 pt-2">
                <section>
                    <h2 class="mb-4">Structure Data</h2>
                    <table class="table">
                        <tbody>
                        <tr>
                            <th scope="row">SMILES</th>
                            <td class="col-10"><small class="text-break">{{ compound.structure.smiles }}</small>
                            </td>
                        </tr>
                        {% comment %}
                        <tr>
                            <th scope="row">Std. InChIKey</th>
                            <td class="col-10"><small class="text-break">{{ compound.annotated_inchikey }}</small>
                            </td>
                        </tr>
                        {% endcomment %}
                        <tr>
                            <th scope="row">Std. InChI</th>
                            <td class="col-10"><small class="text-break">{{ inchis.standard.inchi.string }}</small>
                            </td>
                        </tr>
                        <tr>
                            <th class="col-1">Formula</th>
                            <td class="col-1"><small>{{ formula }}</small></td>
                        </tr>
                        <tr>
                            <th class="col-1">Weight</th>
                            <td class="col-1"><small>{{ weight }}</small></td>
                        </tr>
                        </tbody>
                    </table>
                </section>
                <section>
                    <h2 class="mt-4 mb-4">Structure Identifier</h2>
                    <div class="card"><div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">NCI/CADD Identifier</th>
                            <th scope="col" class="text-center">Is Parent</th>
                            <th scope="col" class="text-center">Parent Structure (CID)</th>
                            <th scope="col" class="text-center d-none d-md-block">Child Count</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for k, v in parents.items %}
                        <tr>
                            <td class="col-4">
                                <div class="d-flex"><span class="badge bg-secondary {{ k|lower }}-label me-2">{{ k }}</span><small class="d-lg-none d-xl-block">{{ v.identifier|default_if_none:"N/A" }}</small></div>
                            </td>
                            <td class="col-1 text-center">
                                {{ v.is_parent|yesno }}
                            </td>
                            <td class="col-3 text-center">
                                {% url 'compounds' v.structure.compound.id as compound_url %}
                                <a class="link-primary" href="{{ compound_url }}">{{ v.structure.compound.id|default_if_none:"N/A" }}</a>
                            </td>
                            <td class="col-3 text-center">
                                {{ v.children_count|default_if_none:"N/A" }}
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">InChIKey</th>
                            <th scope="col" class="text-center">Version</th>
                            <th scope="col" class="text-center">SaveOpt</th>
                            <th scope="col" class="text-center">Software Version</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for k, v in inchis.items %}
                        <tr>
                            <td class="col-4">
                                <div class="d-flex">
                                <span class="badge bg-secondary inchi-label me-2">{{ v.inchi_type.title }}</span><small>{{ v.inchi.key }}</small>
                                </div>
                            </td>
                            <td class="col-1 text-center"><small>{{ v.inchi.version }}</small></td>
                            <td class="col-3 text-center"><small>{{ v.save_opt }}</small></td>
                            <td class="col-3 text-center"><small>{{ v.software_version }}</small></td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    </div></div>
                </section>
                <section>

                </section>
                <section>
                    <h2 class="mb-4 mt-4">Names</h2>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Affinity</th>
                            <th scope="col" class="d-none d-md-block">Type</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for k, v in names.items %}
                            {%  for name in v %}
                            <tr>
                                <td class="col-7">{{ name.name.name }}</td>
                                <td class="col-2"><small class="text-break">{{ k }}</small>
                                <td class="d-none d-md-block"><small class="text-break">{{ name.name_type.public_string }}</small>
                                </td>
                            </tr>
                            {% endfor %}
                        {% endfor %}
                        </tbody>
                    </table>
                </section>

            </div>
        </div>
    </div>
</main>
{% endblock main %}

appsite/neon/templates/cover.html
{% extends "neon-base.html" %}
{# Load the tag library #}
{% load django_bootstrap5 %}

{#{% block style %}#}
{#    <style>#}
{#      .bd-placeholder-img {#}
{#        font-size: 1.125rem;#}
{#        text-anchor: middle;#}
{#        -webkit-user-select: none;#}
{#        -moz-user-select: none;#}
{#        user-select: none;#}
{#      }#}
{##}
{#      @media (min-width: 768px) {#}
{#        .bd-placeholder-img-lg {#}
{#          font-size: 3.5rem;#}
{#        }#}
{#      }#}
{#    </style>#}
{#{% endblock style %}#}

{% block body_class %}d-flex h-100 text-center text-white bg-secondary{% endblock %}
{% block content %}
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
{#        <div>#}
{#            <h3 class="float-md-start mb-0">Cover</h3>#}
{#            <nav class="nav nav-masthead justify-content-center float-md-end">#}
{#                <a class="nav-link active" aria-current="page" href="#">Home</a>#}
{#                <a class="nav-link" href="#">Features</a>#}
{#                <a class="nav-link" href="#">Contact</a>#}
{#            </nav>#}
{#        </div>#}
    </header>

    <main class="px-3">
        <h1>Chemical Identifier Resolver NEON</h1>
        <p class="lead">The future relaunch of the original Resolver
            <a class="link-light link-offset-2 link-opacity-50-hover d-none d-sm-block" href="https://cactus.nci.nih.gov/chemical/structure">
                https://cactus.nci.nih.gov/chemical/structure
            </a>
        </p>
        <p class="pt-5">
            <a href="{% url 'cir' %}" class="btn btn-lg btn-outline-light border-white">Start</a>
        </p>
    </main>

    <footer class="mt-auto text-white-50">
        <p>&#169 NCI/CADD, Xemisty GmbH and Markus Sitzmann 2022-{% now "Y" %}</p>
    </footer>
</div>
{% endblock content %}

appsite/neon/templates/editor.html
<div class="modal" id="editorModal" tabindex="-1" aria-labelledby="editorModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editorModalLabel">Structure Editor</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="jsme-box"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="insertSmiles()">Finish</button>
            </div>
        </div>
    </div>
</div>

appsite/neon/templates/neon.html
{% extends "neon-base.html" %}
{# Load the tag library #}
{% load django_bootstrap5 %}

{# Load CSS and JavaScript #}
{#% bootstrap_css %#}
{#% bootstrap_javascript %#}

{# Display django.contrib.messages as Bootstrap alerts #}
{#% bootstrap_messages %#}

{# Display a form #}
{% block content %}
<form action="/url/to/submit/" method="post" class="form">
  {% csrf_token %}

  {% bootstrap_form form %}

  {% bootstrap_button button_type="submit" content="OK" button_class="btn-secondary" %}
  {% bootstrap_button button_type="reset" content="Cancel" %}

</form>
{%  endblock %}

appsite/neon/templates/resolver.html
{% extends "neon-base.html" %}
{# Load the tag library #}
{% load static %}
{% load django_bootstrap5 django_bootstrap_input_group %}

{% block body_class %}d-flex flex-column h-100{% endblock %}

{% block main %}
    <div class="container-fluid" id="main-container">
        <div class="mt-5">
            <div class="container-fluid p-5">

                <div class="modal" id="editorModal" tabindex="-1" aria-labelledby="editorModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog modal-fullscreen">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="editorModalLabel">Structure Editor</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div id="jsme-box"></div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"
                                        onclick="insertSmiles()">Finish
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <form action="{% url 'resolver-request' %}" method="post" class="form">
                    {% csrf_token %}
                    <div class="mb-3"><label class="form-label" for="id_identifier">Convert:</label>
                        <div class="input-group">
                            <input type="text" class="form-control form-control-lg" placeholder="Structure Identifier"
                                   aria-label="Input identifier string" name="identifier" required id="id_identifier">
                            <button class="btn btn-dark" type="button" onclick="clearInput()"><span
                                    class="bi-x"></span></button>
                            <button class="btn btn-dark" type="button" data-bs-toggle="modal" onclick="insertStructure()"
                                    data-bs-target="#editorModal">
                                <span class="bi-pencil-fill"></span>
                            </button>
                        </div>
                    </div>
                    {% bootstrap_field form.representation %}
                    {% bootstrap_button id="submit-button" button_type="submit" content="Submit" button_class="btn-dark" %}
                </form>

            </div>
        </div>
    </div>
{% endblock main %}

{% block javascript %}
    <script src="{% static 'neon/assets/jquery/jquery-3.6.4.min.js' %}"></script>
    <script src="{% static 'neon/assets/jsme/jsme.nocache.js' %}"></script>
    <script src="{% static 'neon/assets/neon.js' %}"></script>
{% endblock javascript %}

appsite/neon/templates/structure-form.html
{% load django_bootstrap5 django_bootstrap_input_group %}

<form action="{% url 'cir-request' %}" method="post" class="form">
    {% csrf_token %}
    <div class="mb-3"><label class="form-label" for="id_identifier">Convert:</label>
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Structure Identifier"
                   aria-label="Input identifier string" name="identifier" required id="id_identifier">
            <button class="btn btn-dark" type="button" onclick="clearInput()"><span
                    class="bi-x"></span></button>
            <button class="btn btn-dark" type="button" data-bs-toggle="modal" onclick="insertStructure()"
                    data-bs-target="#editorModal">
                <span class="bi-pencil-fill"></span>
            </button>
        </div>
    </div>
    {% bootstrap_field form.representation %}
    {% bootstrap_button id="submit-button" button_type="submit" content="Submit" button_class="btn-dark" %}
</form>